debugging

diff --git a/.github/workflows/run.yml b/.github/workflows/run.yml
--- a/.github/workflows/run.yml
+++ b/.github/workflows/run.yml
@@ -38,6 +38,28 @@ jobs:
       #  Run decoder using prebuilt Docker image
       # - name: Download CAIDA dataset
       #   run: wget https://drive.google.com/file/d/1z-YyZi-STs6A3-CB07Lh_0qJBXcO2r4u/view?usp=sharing -O directed_caida.pkl
+
+      # 2️. Download AS dataset from GitHub Release
+      - name: Fetch directed_caida.pkl from GitHub Release
+        run: |
+          echo " Downloading CAIDA.pkl from GitHub Releases..."
+          wget -O directed_caida.pkl https://github.com/ruth22soft/neural_subgraph_new_version/releases/tag/AS 
+          echo " Verifying downloaded file..."
+          file directed_caida.pkl
+
+          FILE_SIZE=$(stat -c%s amazon0302.pkl)
+          echo "File size: $FILE_SIZE bytes"
+
+          if [ $FILE_SIZE -lt 100000 ]; then
+            echo " ERROR: directed_caida.pkl is too small. Likely not downloaded correctly!"
+            exit 1
+          fi
+
+          if file amazon0302.pkl | grep -Eq "HTML|ASCII|Unicode"; then
+            echo " ERROR: directed_caida.pkl is not a valid binary file!"
+            exit 1
+          fi
+          echo " directed_caida.pkl verified as binary."
         
       - name: Run decoder in Docker container
         run: |
